// mpv port by the mpv-retro-shaders Contributors (c) 2022
// This file includes additional modifications by TyRaS-SW, 2026
// Generated by mpv-libretro

//!PARAM CRTgamma
//!DESC Gamma of simulated CRT
//!TYPE CONSTANT float
//!MINIMUM 0.7
//!MAXIMUM 4
2.4

//!PARAM R
//!DESC Radius of curvature
//!TYPE CONSTANT float
//!MINIMUM 0.5
//!MAXIMUM 10
3.5

//!PARAM angle_x
//!DESC Tilt X
//!TYPE CONSTANT float
//!MINIMUM -1
//!MAXIMUM 1
0

//!PARAM angle_y
//!DESC Tilt Y
//!TYPE CONSTANT float
//!MINIMUM -1
//!MAXIMUM 1
0

//!PARAM aperture_strength
//!DESC Shadow mask strength
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1
0.4

//!PARAM aspect_x
//!DESC Aspect ratio X
//!TYPE CONSTANT float
//!MINIMUM 0.3
//!MAXIMUM 1
1

//!PARAM aspect_y
//!DESC Aspect ratio Y
//!TYPE CONSTANT float
//!MINIMUM 0.3
//!MAXIMUM 1
0.75

//!PARAM cornersize
//!DESC Rounded corner size
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 0.1
0

//!PARAM cornersmooth
//!DESC Border smoothness
//!TYPE CONSTANT float
//!MINIMUM 100
//!MAXIMUM 2000
1000

//!PARAM curvature
//!DESC Enable Curvature
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 1
0

//!PARAM d
//!DESC Distance to screen
//!TYPE CONSTANT float
//!MINIMUM 0.1
//!MAXIMUM 10
2

//!PARAM halation
//!DESC Halation amplitude
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 0.3
0.1

//!PARAM mask_type
//!DESC Mask (none, aperture, slot, delta)
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 3
1

//!PARAM monitorgamma
//!DESC Gamma of output display
//!TYPE CONSTANT float
//!MINIMUM 0.7
//!MAXIMUM 4
2.2

//!PARAM overscan_x
//!DESC Overscan X
//!TYPE CONSTANT float
//!MINIMUM 0.8
//!MAXIMUM 1.2
1

//!PARAM overscan_y
//!DESC Overscan Y
//!TYPE CONSTANT float
//!MINIMUM 0.8
//!MAXIMUM 1.2
1

//!PARAM phosphor_amplitude
//!DESC Phosphor persistence amplitude
//!TYPE CONSTANT float
//!MINIMUM 0
//!MAXIMUM 0.2
0.04

//!PARAM phosphor_power
//!DESC Phosphor decay power
//!TYPE CONSTANT float
//!MINIMUM 0.5
//!MAXIMUM 3
1.2

//!PARAM width
//!DESC Halation blur width
//!TYPE CONSTANT float
//!MINIMUM 0.1
//!MAXIMUM 4
2

//!TEXTURE delta
//!SIZE 4 2
//!BORDER REPEAT
//!FILTER NEAREST
//!FORMAT rgba8
ff0000ffffff00ff00ffffff0000ffff00ffffff0000ffffff0000ffffff00ff

//!TEXTURE slot
//!SIZE 10 4
//!BORDER REPEAT
//!FILTER NEAREST
//!FORMAT rgba8
ff0000ffff00ffff0000ffff00ff00ff00ff00ffff0000ffff00ffff0000ffff00ff00ff00ff00ff000000ff0000ffff0000ffff00ff00ff00ff00ffff0000ffff0000ff000000ff000000ff000000ffff0000ffff00ffff0000ffff00ff00ff00ff00ffff0000ffff00ffff0000ffff00ff00ff00ff00ffff0000ffff0000ff000000ff000000ff000000ff000000ff0000ffff0000ffff00ff00ff00ff00ff

//!TEXTURE aperture
//!SIZE 4 1
//!BORDER REPEAT
//!FILTER NEAREST
//!FORMAT rgba8
ff0000ffffff00ff00ffffff0000ffff

//!HOOK MAIN
//!COMPONENTS 4
//!DESC sRGB to linear RGB
//!SAVE MAIN_RGB
//!BIND HOOKED

vec4 hook() {
	return linearize(HOOKED_tex(HOOKED_pos));
}

//!HOOK MAIN
//!COMPONENTS 2
//!DESC store viewport size
//!SAVE VIEWPORT
//!WIDTH OUTPUT.width
//!HEIGHT OUTPUT.height

vec4 hook() {
	return vec4(target_size, 0.0, 0.0);
}

//!HOOK MAIN
//!COMPONENTS 4
//!DESC phosphor_apply.slang
//!SAVE internal1
//!BIND HOOKED
//!BIND MAIN_RGB
//!BIND VIEWPORT

vec4 vertex_gl_Position;
struct _params_ {
    float phosphor_power, phosphor_amplitude, CRTgamma, width, aspect_x, aspect_y, d, R, angle_x, angle_y, aperture_strength, halation, curvature, cornersize, cornersmooth, overscan_x, overscan_y, monitorgamma, mask_type;
} params = _params_(float(phosphor_power), float(phosphor_amplitude), float(CRTgamma), float(width), float(aspect_x), float(aspect_y), float(d), float(R), float(angle_x), float(angle_y), float(aperture_strength), float(halation), float(curvature), float(cornersize), float(cornersmooth), float(overscan_x), float(overscan_y), float(monitorgamma), float(mask_type));
struct _global_ {
    vec4 SourceSize;
    vec4 OriginalSize;
    vec4 OutputSize;
    uint FrameCount;
    vec4 FinalViewportSize;
    vec4 internal1Size;
    mat4 MVP;
} global = _global_(vec4(MAIN_RGB_size, MAIN_RGB_pt), vec4(MAIN_RGB_size, MAIN_RGB_pt), vec4(target_size, 1. / target_size.x, 1. / target_size.y), uint(frame), vec4(VIEWPORT_size, VIEWPORT_pt), vec4(target_size, 1. / target_size.x, 1. / target_size.y), mat4(1.));
vec2 vertex_aspect = vec2(params.aspect_x, params.aspect_y);
vec2 vertex_angle = vec2(params.angle_x, params.angle_y);
vec2 vertex_overscan = vec2(params.overscan_x, params.overscan_y);
int vertex_mask_picker = int(params.mask_type);
const float vertex_gamma = 2.2;
vec4 Position = vec4(HOOKED_pos, 0., 1.);
vec2 TexCoord = HOOKED_pos;
vec2 vTexCoord;
void vertex_main() {
    vertex_gl_Position = global.MVP * Position;
    vTexCoord = TexCoord;
}

vec2 fragment_aspect = vec2(params.aspect_x, params.aspect_y);
vec2 fragment_angle = vec2(params.angle_x, params.angle_y);
vec2 fragment_overscan = vec2(params.overscan_x, params.overscan_y);
int fragment_mask_picker = int(params.mask_type);
const float fragment_gamma = 2.2;
vec4 FragColor;
#define Source MAIN_RGB_raw
#define PassFeedback1 MAIN_RGB_raw
void fragment_main() {
    vec4 screen = texture(Source, vTexCoord);
    vec4 phosphor = texture(PassFeedback1, vTexCoord);
    vec3 cscrn = pow(screen.rgb, vec3(fragment_gamma));
    vec3 cphos = pow(phosphor.rgb, vec3(fragment_gamma));
    float t = 255. * phosphor.a + fract(phosphor.b * 255. / 4.) * 1024.;
    cphos *= vec3(params.phosphor_amplitude * pow(t, -params.phosphor_power));
    vec3 col = pow(cscrn + cphos, vec3(1. / fragment_gamma));
    FragColor = vec4(col, 1.);
}

vec4 hook() {
    vertex_main();
    fragment_main();
    return FragColor;
}


//!HOOK MAIN
//!COMPONENTS 4
//!DESC phosphor_update.slang
//!WIDTH internal1.width 1 *
//!HEIGHT internal1.height 1 *
//!SAVE phosphor
//!BIND VIEWPORT
//!BIND HOOKED
//!BIND MAIN_RGB
//!BIND internal1

vec4 vertex_gl_Position;
struct _params_ {
    float phosphor_power, phosphor_amplitude, CRTgamma, width, aspect_x, aspect_y, d, R, angle_x, angle_y, aperture_strength, halation, curvature, cornersize, cornersmooth, overscan_x, overscan_y, monitorgamma, mask_type;
} params = _params_(float(phosphor_power), float(phosphor_amplitude), float(CRTgamma), float(width), float(aspect_x), float(aspect_y), float(d), float(R), float(angle_x), float(angle_y), float(aperture_strength), float(halation), float(curvature), float(cornersize), float(cornersmooth), float(overscan_x), float(overscan_y), float(monitorgamma), float(mask_type));
struct _global_ {
    vec4 SourceSize;
    vec4 OriginalSize;
    vec4 OutputSize;
    uint FrameCount;
    vec4 FinalViewportSize;
    vec4 internal1Size;
    mat4 MVP;
} global = _global_(vec4(internal1_size, internal1_pt), vec4(MAIN_RGB_size, MAIN_RGB_pt), vec4(target_size, 1. / target_size.x, 1. / target_size.y), uint(frame), vec4(VIEWPORT_size, VIEWPORT_pt), vec4(internal1_size, internal1_pt), mat4(1.));
vec2 vertex_aspect = vec2(params.aspect_x, params.aspect_y);
vec2 vertex_angle = vec2(params.angle_x, params.angle_y);
vec2 vertex_overscan = vec2(params.overscan_x, params.overscan_y);
int vertex_mask_picker = int(params.mask_type);
const float vertex_gamma = 2.2;
vec4 Position = vec4(HOOKED_pos, 0., 1.);
vec2 TexCoord = HOOKED_pos;
vec2 vTexCoord;
void vertex_main() {
    vertex_gl_Position = global.MVP * Position;
    vTexCoord = TexCoord * 1.0001;
}

vec2 fragment_aspect = vec2(params.aspect_x, params.aspect_y);
vec2 fragment_angle = vec2(params.angle_x, params.angle_y);
vec2 fragment_overscan = vec2(params.overscan_x, params.overscan_y);
int fragment_mask_picker = int(params.mask_type);
const float fragment_gamma = 2.2;
vec4 FragColor;
#define Source internal1_raw
#define phosphorFeedback internal1_raw
void fragment_main() {
    vec4 screen = texture(Source, vTexCoord);
    vec4 phosphor = texture(phosphorFeedback, vTexCoord);
    vec3 lum = vec3(0.299, 0.587, 0.114);
    float bscrn = dot(pow(screen.rgb, vec3(fragment_gamma)), lum);
    float bphos = dot(pow(phosphor.rgb, vec3(fragment_gamma)), lum);
    float t = 1. + 255. * phosphor.a + fract(phosphor.b * 255. / 4.) * 1024.;
    bphos = t > 1023. ? 0. : bphos * pow(t, -params.phosphor_power);
    FragColor = bscrn >= bphos ? vec4(screen.rg, floor(screen.b * 255. / 4.) * 4. / 255., 1. / 255.) : vec4(phosphor.rg, (floor(phosphor.b * 255. / 4.) * 4. + floor(t / 256.)) / 255., fract(t / 256.) * 256. / 255.);
}

vec4 hook() {
    vertex_main();
    fragment_main();
    return FragColor;
}


//!HOOK MAIN
//!COMPONENTS 4
//!DESC gaussx.slang
//!WIDTH phosphor.width 1 *
//!HEIGHT phosphor.height 1 *
//!SAVE internal2
//!BIND VIEWPORT
//!BIND MAIN_RGB
//!BIND phosphor
//!BIND internal1
//!BIND HOOKED

vec4 vertex_gl_Position;
struct _params_ {
    float phosphor_power, phosphor_amplitude, CRTgamma, width, aspect_x, aspect_y, d, R, angle_x, angle_y, aperture_strength, halation, curvature, cornersize, cornersmooth, overscan_x, overscan_y, monitorgamma, mask_type;
} params = _params_(float(phosphor_power), float(phosphor_amplitude), float(CRTgamma), float(width), float(aspect_x), float(aspect_y), float(d), float(R), float(angle_x), float(angle_y), float(aperture_strength), float(halation), float(curvature), float(cornersize), float(cornersmooth), float(overscan_x), float(overscan_y), float(monitorgamma), float(mask_type));
struct _global_ {
    vec4 SourceSize;
    vec4 OriginalSize;
    vec4 OutputSize;
    uint FrameCount;
    vec4 FinalViewportSize;
    vec4 internal1Size;
    mat4 MVP;
} global = _global_(vec4(phosphor_size, phosphor_pt), vec4(MAIN_RGB_size, MAIN_RGB_pt), vec4(target_size, 1. / target_size.x, 1. / target_size.y), uint(frame), vec4(VIEWPORT_size, VIEWPORT_pt), vec4(internal1_size, internal1_pt), mat4(1.));
vec2 vertex_aspect = vec2(params.aspect_x, params.aspect_y);
vec2 vertex_angle = vec2(params.angle_x, params.angle_y);
vec2 vertex_overscan = vec2(params.overscan_x, params.overscan_y);
int vertex_mask_picker = int(params.mask_type);
const float vertex_gamma = 2.2;
vec4 Position = vec4(HOOKED_pos, 0., 1.);
vec2 TexCoord = HOOKED_pos;
vec2 v_texCoord;
vec4 v_coeffs;
void vertex_main() {
    vertex_gl_Position = global.MVP * Position;
    v_texCoord = TexCoord;
    float wid = params.width.x * global.SourceSize.x / (320. * vertex_aspect.x);
    v_coeffs = exp(vec4(1., 4., 9., 16.) * vec4(-1. / wid / wid));
}

vec2 fragment_aspect = vec2(params.aspect_x, params.aspect_y);
vec2 fragment_angle = vec2(params.angle_x, params.angle_y);
vec2 fragment_overscan = vec2(params.overscan_x, params.overscan_y);
int fragment_mask_picker = int(params.mask_type);
const float fragment_gamma = 2.2;
vec4 FragColor;
#define internal1 internal1_raw
void fragment_main() {
    vec3 sum = vec3(0.);
    float onex = 1. / global.SourceSize.x;
    sum += pow(texture(internal1, v_texCoord + vec2(-4. * onex, 0.)).rgb, vec3(fragment_gamma)) * vec3(v_coeffs.w);
    sum += pow(texture(internal1, v_texCoord + vec2(-3. * onex, 0.)).rgb, vec3(fragment_gamma)) * vec3(v_coeffs.z);
    sum += pow(texture(internal1, v_texCoord + vec2(-2. * onex, 0.)).rgb, vec3(fragment_gamma)) * vec3(v_coeffs.y);
    sum += pow(texture(internal1, v_texCoord + vec2(-1. * onex, 0.)).rgb, vec3(fragment_gamma)) * vec3(v_coeffs.x);
    sum += pow(texture(internal1, v_texCoord).rgb, vec3(fragment_gamma));
    sum += pow(texture(internal1, v_texCoord + vec2(+1. * onex, 0.)).rgb, vec3(fragment_gamma)) * vec3(v_coeffs.x);
    sum += pow(texture(internal1, v_texCoord + vec2(+2. * onex, 0.)).rgb, vec3(fragment_gamma)) * vec3(v_coeffs.y);
    sum += pow(texture(internal1, v_texCoord + vec2(+3. * onex, 0.)).rgb, vec3(fragment_gamma)) * vec3(v_coeffs.z);
    sum += pow(texture(internal1, v_texCoord + vec2(+4. * onex, 0.)).rgb, vec3(fragment_gamma)) * vec3(v_coeffs.w);
    float norm = 1. / (1. + 2. * (v_coeffs.x + v_coeffs.y + v_coeffs.z + v_coeffs.w));
    FragColor = vec4(pow(sum * vec3(norm), vec3(1.0 / fragment_gamma)), 1.);
}

vec4 hook() {
    vertex_main();
    fragment_main();
    return FragColor;
}


//!HOOK MAIN
//!COMPONENTS 4
//!DESC gaussy.slang
//!WIDTH internal2.width 1 *
//!HEIGHT internal2.height 1 *
//!SAVE blur
//!BIND HOOKED
//!BIND VIEWPORT
//!BIND internal2
//!BIND MAIN_RGB
//!BIND internal1

vec4 vertex_gl_Position;
struct _params_ {
    float phosphor_power, phosphor_amplitude, CRTgamma, width, aspect_x, aspect_y, d, R, angle_x, angle_y, aperture_strength, halation, curvature, cornersize, cornersmooth, overscan_x, overscan_y, monitorgamma, mask_type;
} params = _params_(float(phosphor_power), float(phosphor_amplitude), float(CRTgamma), float(width), float(aspect_x), float(aspect_y), float(d), float(R), float(angle_x), float(angle_y), float(aperture_strength), float(halation), float(curvature), float(cornersize), float(cornersmooth), float(overscan_x), float(overscan_y), float(monitorgamma), float(mask_type));
struct _global_ {
    vec4 SourceSize;
    vec4 OriginalSize;
    vec4 OutputSize;
    uint FrameCount;
    vec4 FinalViewportSize;
    vec4 internal1Size;
    mat4 MVP;
} global = _global_(vec4(internal2_size, internal2_pt), vec4(MAIN_RGB_size, MAIN_RGB_pt), vec4(target_size, 1. / target_size.x, 1. / target_size.y), uint(frame), vec4(VIEWPORT_size, VIEWPORT_pt), vec4(internal1_size, internal1_pt), mat4(1.));
vec2 vertex_aspect = vec2(params.aspect_x, params.aspect_y);
vec2 vertex_angle = vec2(params.angle_x, params.angle_y);
vec2 vertex_overscan = vec2(params.overscan_x, params.overscan_y);
int vertex_mask_picker = int(params.mask_type);
const float vertex_gamma = 2.2;
vec4 Position = vec4(HOOKED_pos, 0., 1.);
vec2 TexCoord = HOOKED_pos;
vec2 v_texCoord;
vec4 v_coeffs;
void vertex_main() {
    vertex_gl_Position = global.MVP * Position;
    v_texCoord = TexCoord;
    float wid = params.width.x * global.SourceSize.y / (320. * vertex_aspect.y);
    v_coeffs = exp(vec4(1., 4., 9., 16.) * vec4(-1. / wid / wid));
}

vec2 fragment_aspect = vec2(params.aspect_x, params.aspect_y);
vec2 fragment_angle = vec2(params.angle_x, params.angle_y);
vec2 fragment_overscan = vec2(params.overscan_x, params.overscan_y);
int fragment_mask_picker = int(params.mask_type);
const float fragment_gamma = 2.2;
vec4 FragColor;
#define Source internal2_raw
void fragment_main() {
    vec3 sum = vec3(0.);
    float oney = 1. / global.SourceSize.y;
    sum += pow(texture(Source, v_texCoord + vec2(0., -4. * oney)).rgb, vec3(fragment_gamma)) * vec3(v_coeffs.w);
    sum += pow(texture(Source, v_texCoord + vec2(0., -3. * oney)).rgb, vec3(fragment_gamma)) * vec3(v_coeffs.z);
    sum += pow(texture(Source, v_texCoord + vec2(0., -2. * oney)).rgb, vec3(fragment_gamma)) * vec3(v_coeffs.y);
    sum += pow(texture(Source, v_texCoord + vec2(0., -1. * oney)).rgb, vec3(fragment_gamma)) * vec3(v_coeffs.x);
    sum += pow(texture(Source, v_texCoord).rgb, vec3(fragment_gamma));
    sum += pow(texture(Source, v_texCoord + vec2(0., +1. * oney)).rgb, vec3(fragment_gamma)) * vec3(v_coeffs.x);
    sum += pow(texture(Source, v_texCoord + vec2(0., +2. * oney)).rgb, vec3(fragment_gamma)) * vec3(v_coeffs.y);
    sum += pow(texture(Source, v_texCoord + vec2(0., +3. * oney)).rgb, vec3(fragment_gamma)) * vec3(v_coeffs.z);
    sum += pow(texture(Source, v_texCoord + vec2(0., +4. * oney)).rgb, vec3(fragment_gamma)) * vec3(v_coeffs.w);
    float norm = 1. / (1. + 2. * (v_coeffs.x + v_coeffs.y + v_coeffs.z + v_coeffs.w));
    FragColor = vec4(pow(sum * vec3(norm), vec3(1.0 / fragment_gamma)), 1.);
}

vec4 hook() {
    vertex_main();
    fragment_main();
    return FragColor;
}


//!HOOK MAIN
//!COMPONENTS 4
//!DESC crt-geom-deluxe.slang
//!WIDTH blur.width 1 *
//!HEIGHT blur.height 1 *
//!BIND slot
//!BIND blur
//!BIND aperture
//!BIND delta
//!BIND internal1
//!BIND VIEWPORT
//!BIND MAIN_RGB
//!BIND HOOKED

vec4 vertex_gl_Position;
struct _params_ {
    float phosphor_power, phosphor_amplitude, CRTgamma, width, aspect_x, aspect_y, d, R, angle_x, angle_y, aperture_strength, halation, curvature, cornersize, cornersmooth, overscan_x, overscan_y, monitorgamma, mask_type;
} params = _params_(float(phosphor_power), float(phosphor_amplitude), float(CRTgamma), float(width), float(aspect_x), float(aspect_y), float(d), float(R), float(angle_x), float(angle_y), float(aperture_strength), float(halation), float(curvature), float(cornersize), float(cornersmooth), float(overscan_x), float(overscan_y), float(monitorgamma), float(mask_type));
struct _global_ {
    vec4 SourceSize;
    vec4 OriginalSize;
    vec4 OutputSize;
    uint FrameCount;
    vec4 FinalViewportSize;
    vec4 internal1Size;
    mat4 MVP;
} global = _global_(vec4(blur_size, blur_pt), vec4(MAIN_RGB_size, MAIN_RGB_pt), vec4(target_size, 1. / target_size.x, 1. / target_size.y), uint(frame), vec4(VIEWPORT_size, VIEWPORT_pt), vec4(internal1_size, internal1_pt), mat4(1.));
vec2 vertex_aspect = vec2(params.aspect_x, params.aspect_y);
vec2 vertex_angle = vec2(params.angle_x, params.angle_y);
vec2 vertex_overscan = vec2(params.overscan_x, params.overscan_y);
int vertex_mask_picker = int(params.mask_type);
const float vertex_gamma = 2.2;
vec4 Position = vec4(HOOKED_pos, 0., 1.);
vec2 TexCoord = HOOKED_pos;
vec2 v_texCoord;
vec2 v_sinangle;
vec2 v_cosangle;
vec3 v_stretch;
vec2 v_one;
float vertex_intersect(vec2 xy, vec2 sinangle, vec2 cosangle) {
    float A = dot(xy, xy) + params.d.x * params.d.x;
    float B = 2. * (params.R.x * (dot(xy, sinangle) - params.d.x * cosangle.x * cosangle.y) - params.d.x * params.d.x);
    float C = params.d.x * params.d.x + 2. * params.R.x * params.d.x * cosangle.x * cosangle.y;
    return (-B - sqrt(B * B - 4. * A * C)) / (2. * A);
}

vec2 vertex_bkwtrans(vec2 xy, vec2 sinangle, vec2 cosangle) {
    float c = vertex_intersect(xy, sinangle, cosangle);
    vec2 pt = vec2(c) * xy;
    pt -= vec2(-params.R.x) * sinangle;
    pt /= vec2(params.R.x);
    vec2 tang = sinangle / cosangle;
    vec2 poc = pt / cosangle;
    float A = dot(tang, tang) + 1.;
    float B = -2. * dot(poc, tang);
    float C = dot(poc, poc) - 1.;
    float a = (-B + sqrt(B * B - 4. * A * C)) / (2. * A);
    vec2 uv = (pt - a * sinangle) / cosangle;
    float r = max(abs(params.R.x * acos(a)), 0.00001);
    return uv * r / sin(r / params.R.x);
}

vec2 vertex_fwtrans(vec2 uv, vec2 sinangle, vec2 cosangle) {
    float r = max(abs(sqrt(dot(uv, uv))), 0.00001);
    uv *= sin(r / params.R.x) / r;
    float x = 1. - cos(r / params.R.x);
    float D = params.d.x / params.R.x + x * cosangle.x * cosangle.y + dot(uv, sinangle);
    return params.d.x * (uv * cosangle - x * sinangle) / D;
}

vec3 vertex_maxscale(vec2 sinangle, vec2 cosangle) {
    vec2 c = vertex_bkwtrans(-params.R.x * sinangle / (1. + params.R.x / params.d.x * cosangle.x * cosangle.y), sinangle, cosangle);
    vec2 a = vec2(0.5, 0.5) * vertex_aspect.xy;
    vec2 lo = vec2(vertex_fwtrans(vec2(-a.x, c.y), sinangle, cosangle).x, vertex_fwtrans(vec2(c.x, -a.y), sinangle, cosangle).y) / vertex_aspect.xy;
    vec2 hi = vec2(vertex_fwtrans(vec2(+a.x, c.y), sinangle, cosangle).x, vertex_fwtrans(vec2(c.x, +a.y), sinangle, cosangle).y) / vertex_aspect.xy;
    return vec3((hi + lo) * vertex_aspect.xy * 0.5, max(hi.x - lo.x, hi.y - lo.y));
}

void vertex_main() {
    vertex_gl_Position = global.MVP * Position;
    v_texCoord = TexCoord;
    vec2 ang;
    ang = vertex_angle.xy;
    v_sinangle = sin(ang);
    v_cosangle = cos(ang);
    v_stretch = vertex_maxscale(v_sinangle, v_cosangle);
    v_one = 1. / global.SourceSize.xy;
}

vec2 fragment_aspect = vec2(params.aspect_x, params.aspect_y);
vec2 fragment_angle = vec2(params.angle_x, params.angle_y);
vec2 fragment_overscan = vec2(params.overscan_x, params.overscan_y);
int fragment_mask_picker = int(params.mask_type);
const float fragment_gamma = 2.2;
vec4 FragColor;
#define blur blur_raw
#define internal1 internal1_raw
float fragment_intersect(vec2 xy, vec2 sinangle, vec2 cosangle) {
    float A = dot(xy, xy) + params.d.x * params.d.x;
    float B = 2. * (params.R.x * (dot(xy, sinangle) - params.d.x * cosangle.x * cosangle.y) - params.d.x * params.d.x);
    float C = params.d.x * params.d.x + 2. * params.R.x * params.d.x * cosangle.x * cosangle.y;
    return (-B - sqrt(B * B - 4. * A * C)) / (2. * A);
}

vec2 fragment_bkwtrans(vec2 xy, vec2 sinangle, vec2 cosangle) {
    float c = fragment_intersect(xy, sinangle, cosangle);
    vec2 pt = vec2(c) * xy;
    pt -= vec2(-params.R.x) * sinangle;
    pt /= vec2(params.R.x);
    vec2 tang = sinangle / cosangle;
    vec2 poc = pt / cosangle;
    float A = dot(tang, tang) + 1.;
    float B = -2. * dot(poc, tang);
    float C = dot(poc, poc) - 1.;
    float a = (-B + sqrt(B * B - 4. * A * C)) / (2. * A);
    vec2 uv = (pt - a * sinangle) / cosangle;
    float r = max(abs(params.R.x * acos(a)), 0.00001);
    return uv * r / sin(r / params.R.x);
}

vec2 fragment_transform(vec2 coord, vec3 stretch, vec2 sinangle, vec2 cosangle) {
    coord = (coord - vec2(0.5)) * fragment_aspect.xy * stretch.z + stretch.xy;
    return fragment_bkwtrans(coord, sinangle, cosangle) / fragment_overscan.xy / fragment_aspect.xy + vec2(0.5);
}

float fragment_corner(vec2 coord) {
    coord = (coord - vec2(0.5)) * fragment_overscan.xy + vec2(0.5);
    coord = min(coord, vec2(1.) - coord) * fragment_aspect.xy;
    vec2 cdist = vec2(params.cornersize.x);
    coord = cdist - min(coord, cdist);
    float dist = sqrt(dot(coord, coord));
    return clamp((max(cdist.x, 0.001) - dist) * params.cornersmooth.x, 0., 1.);
}

vec4 fragment_scanlineWeights(float distance, vec4 color) {
    vec4 wid = 0.3 + 0.1 * pow(color, vec4(3.));
    vec4 weights = vec4(distance / wid);
    return 0.4 * exp(-weights * weights) / wid;
}

void fragment_main() {
    vec2 xy;
    if (params.curvature.x > 0.5) xy = fragment_transform(v_texCoord, v_stretch, v_sinangle, v_cosangle); else xy = (v_texCoord - vec2(0.5)) / fragment_overscan.xy + vec2(0.5);
    vec2 xy0 = xy;
    float cval = fragment_corner(xy);
    vec2 ratio_scale = xy * global.SourceSize.xy - vec2(0.5);
    float oversample_filter = fwidth(ratio_scale.y);
    vec2 uv_ratio = fract(ratio_scale);
    xy = (floor(ratio_scale) + vec2(0.5)) / global.SourceSize.xy;
    vec4 coeffs = 3.1415927 * vec4(1. + uv_ratio.x, uv_ratio.x, 1. - uv_ratio.x, 2. - uv_ratio.x);
    coeffs = max(abs(coeffs), 0.00001);
    coeffs = 2. * sin(coeffs) * sin(coeffs / 2.) / (coeffs * coeffs);
    coeffs /= dot(coeffs, vec4(1.));
    vec4 col = clamp(texture(internal1, xy + vec2(-v_one.x, 0.)) * coeffs.x + texture(internal1, xy) * coeffs.y + texture(internal1, xy + vec2(v_one.x, 0.)) * coeffs.z + texture(internal1, xy + vec2(2. * v_one.x, 0.)) * coeffs.w, 0., 1.);
    vec4 col2 = clamp(texture(internal1, xy + vec2(-v_one.x, v_one.y)) * coeffs.x + texture(internal1, xy + vec2(0., v_one.y)) * coeffs.y + texture(internal1, xy + v_one) * coeffs.z + texture(internal1, xy + vec2(2. * v_one.x, v_one.y)) * coeffs.w, 0., 1.);
    col = pow(col, vec4(params.CRTgamma.x));
    col2 = pow(col2, vec4(params.CRTgamma.x));
    vec4 weights = fragment_scanlineWeights(uv_ratio.y, col);
    vec4 weights2 = fragment_scanlineWeights(1. - uv_ratio.y, col2);
    uv_ratio.y = uv_ratio.y + 1. / 3. * oversample_filter;
    weights = (weights + fragment_scanlineWeights(uv_ratio.y, col)) / 3.;
    weights2 = (weights2 + fragment_scanlineWeights(abs(1. - uv_ratio.y), col2)) / 3.;
    uv_ratio.y = uv_ratio.y - 2. / 3. * oversample_filter;
    weights = weights + fragment_scanlineWeights(abs(uv_ratio.y), col) / 3.;
    weights2 = weights2 + fragment_scanlineWeights(abs(1. - uv_ratio.y), col2) / 3.;
    vec3 mul_res = (col * weights + col2 * weights2).rgb;
    vec3 blur = pow(texture(blur, xy0).rgb, vec3(params.CRTgamma.x));
    mul_res = mix(mul_res, blur, params.halation.x) * vec3(cval);
    mul_res = pow(mul_res, vec3(1. / params.monitorgamma.x));
    xy = v_texCoord.xy * vec2(HOOKED_size);
    vec3 mask = vec3(1.);
    if (fragment_mask_picker == 0) {
        FragColor = vec4(mul_res, col.a);
        return;
    } else if (fragment_mask_picker == 1) mask = texture(aperture, xy * 0.3333).rgb; else if (fragment_mask_picker == 2) mask = texture(slot, xy * 0.25).rgb; else mask = texture(delta, xy * 0.49999).rgb;
    mask = mix(vec3(1.), mask, params.aperture_strength.x);
    FragColor = vec4(mul_res * mask, col.a);
}

vec4 hook() {
    vertex_main();
    fragment_main();
    return delinearize(FragColor);
}

