# ===========================
# INPUT DEFAULTS
# ===========================
# DOUBLE RIGHT CLICK FullScreen Cycle ON-OFF
MBTN_LEFT_DBL cycle fullscreen
# RIGHT CLICK MPV Menu
MBTN_RIGHT script-binding select/context-menu
# "ESC" Key also able to open MPV Menu
ESC script-binding select/context-menu

# ===========================
# SHADERS — QUICK ACCESS
# ===========================
CTRL+1 no-osd change-list glsl-shaders set "~~/shaders/KrigBilateral.glsl;~~/shaders/AMD/AMD_FSR1_RT.glsl;~~/shaders/Adaptive_sharpen_lite_RT.glsl"; set deband yes; set user-data/active_shader SH1; show-text "👑1080p→4K Fast"
CTRL+2 no-osd change-list glsl-shaders set "~~/shaders/mpv-retro-shaders/crt-gdv-mini-ultra-trinitron.glsl"; show-text "📺 CRT Trinitron"
CTRL+3 no-osd change-list glsl-shaders set "~~/shaders/mpv-retro-shaders/crt-lottes-fix.glsl"; show-text "📺 CRT Arcade (Lottes)"
CTRL+4 no-osd change-list glsl-shaders set "~~/shaders/mpv-retro-shaders/vhs.glsl"; show-text "CRT VHS"
CTRL+5 no-osd change-list glsl-shaders clr ""; show-text "🧹 Shaders Cleaned"
CTRL+0 no-osd script-message clear-bezel; vf set ""; change-list glsl-shaders clr ""; set deband no; set user-data/active_shader none; set video-zoom 0; set video-pan-x 0; set video-pan-y 0; set panscan 0; set video-aspect-override -1; set video-rotate 0; set contrast 0; set brightness 0; set gamma 0; set saturation 0; set hue 0; show-text "🗑️ ALL Cleaned"