# MPV-SW Capture
# v4.0.1
# ===========================
# INPUT DEFAULTS
# ===========================
input-default-bindings=no
input-builtin-bindings=no

# ===========================
# LAUNCH SHADER (You will start with this when launch MPV)
# ===========================
deband=yes
glsl-shader="~~/shaders/KrigBilateral.glsl"
glsl-shader="~~/shaders/AMD_FSR1_RT.glsl"
glsl-shader="~~/shaders/NVSharpen_scl_RT.glsl"

# ===========================
# ICC Profile AUTOSTART
# ===========================
icc-profile-auto=no

# ===========================
# SCREENSHOTS (Custom format)
# ===========================
screenshot-directory=~~exe_dir/_screenshots
screenshot-format=jpg
screenshot-template="MSC_%td-%tm-%tY_%tH%tM%tS"

# ===========================
# OSD
# ===========================
osd-duration=1000

# ===========================
# Others
# ===========================
title="MPV-SW-Capture"