# ===========================
# INPUT DEFAULTS
# ===========================
input-default-bindings=no
input-builtin-bindings=no

# ===========================
# LAUNCH SHADER (You will start with this when launch MPV)
# ===========================
deband=yes
glsl-shader="~~/shaders/KrigBilateral.glsl"
glsl-shader="~~/shaders/AMD_FSR1_RT.glsl"
glsl-shader="~~/shaders/Adaptive_sharpen_lite_RT.glsl"

# ===========================
# SCREENSHOTS (Custom format)
# ===========================
screenshot-directory=~~exe_dir/_screenshots
screenshot-format=jpg
screenshot-template="MPV_%td-%tm-%tY_%n"