name: Update (releases, shaders, bezels)

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Obtain releases (last 5)
        id: get_releases
        run: |
          curl -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: Bearer ${{ github.token }}" \
               https://api.github.com/repos/${{ github.repository }}/releases?per_page=5 \
               | jq '[.[] | {tag: .tag_name, fecha: .published_at, descripcion: .body}]' > docs/releases.json
          echo "Contain of docs/releases.json:"
          cat docs/releases.json

      - name: Obtener shaders (archivos .glsl)
        run: |
          if [ -d "shaders" ]; then
            curl -H "Accept: application/vnd.github.v3+json" \
                 -H "Authorization: Bearer ${{ github.token }}" \
                 https://api.github.com/repos/${{ github.repository }}/contents/shaders \
                 | jq '[.[] | select(.name | endswith(".glsl")) | .name]' > docs/shaders.json
          else
            echo '[]' > docs/shaders.json
          fi
          echo "Contain of docs/shaders.json:"
          cat docs/shaders.json

      - name: Obtain bezels (.png)
        run: |
          if [ -d "bezels" ]; then
            curl -H "Accept: application/vnd.github.v3+json" \
                 -H "Authorization: Bearer ${{ github.token }}" \
                 https://api.github.com/repos/${{ github.repository }}/contents/bezels \
                 | jq '[.[] | select(.name | endswith(".png")) | .name]' > docs/bezels.json
          else
            echo '[]' > docs/bezels.json
          fi
          echo "Contain of docs/bezels.json:"
          cat docs/bezels.json

      - name: Validate generated JSON
        run: |
          for file in docs/releases.json docs/shaders.json docs/bezels.json; do
            if ! jq empty "$file" 2>/dev/null; then
              echo "❌ Error: $file isn't a valid JSON"
              exit 1
            fi
          done
          echo "✅ All JSON are valid."

      - name: Commit y push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/releases.json docs/shaders.json docs/bezels.json
          # Commit even if there aren't new changes (debug)
          git commit -m "$(date +'%Y-%m-%d %H:%M')" || echo "ℹ️ No changes for commit"
          git push